### ISSUE TITLE
DLL load failed while importing emd_wrap

### ISSUE THREAD

**Issue by eidalex** [PythonOT/POT#188]
Hi there, 
First of all I want to thank you for your amazing detailed work on this package. I would love to use it in my research however I stumbled upon some disagrements during the process. 
I tried to run the tutorial on _"1d Wasserstein for unbalanced distribution"_ but I cannot manage to make it work...
For my configuration I have : Windows 10 Enterprise, Python 3.8.2 and I have created a virtual environment to work in. (I also have cupy-cuda102). I have installed the package using `pip install pot` inside the virtual env.

Now for the detailed problem I have the following message when trying to run the script 

`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/.../WORKSPACE/Python/.../src/optimal_transport/1d_wasserstein_unbalanced_distrib.py", line 3, in <module>
    import ot
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\...\WORKSPACE\Python\...\venv\lib\site-packages\ot\__init__.py", line 25, in <module>
    from . import lp
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\...\WORKSPACE\Python\...\venv\lib\site-packages\ot\lp\__init__.py", line 20, in <module>
    from .emd_wrap import emd_c, check_result, emd_1d_sorted
  File "C:\Program Files\JetBrains\PyCharm 2020.1.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed while importing emd_wrap: Le module spécifié est introuvable.`

I have naviagted through the file explorer and apparently the faulty script is _ot/lp/__init__.py_ which tries to import _.emd_wrap_ at line 20.

`from .emd_wrap import emd_c, check_result, emd_1d_sorted`

Inside the folder there is a .pyd file named _emd_wrap.cp38-win-win_amd64.pyd_ ... I have tried to change its name but well... it does not work.

Would you please help me ? Thanks in advance

**Comment by rflamary** [comment]
Hello,

This file is the dll and it should at least find it. Are you sure the interpreter in PyCharm is using the same python version as when you installed it?

Worst case scenario you should uninstall POT with pip and try to install it from source (it will compile the proper dll/pyd file ). with the following line:
```
pip install -U https://github.com/PythonOT/POT/archive/master.zip
```
if you are using anaconda, you could also install from conda-forge that has the proper dll also.

**Comment by eidalex** [comment]
Thanks a lot for your reactivity ! I have uninstalled POT and installed it from source successfully with your provided instruction. It works like a charm ! (The PyCharm interpreter was well configured) 
Have a nice day !
