### ISSUE TITLE
Conflict with python=3.9 when installing from conda

### ISSUE THREAD

**Issue by zsteve** [PythonOT/POT#268]
## Describe the bug

I'm having an UnsatisfiableError when trying to install `pot` using `conda` with `python=3.9`. To test this, I created a fresh conda environment:
Python version
```
(py39) [syz@archlinux ~]$ python --version
Python 3.9.6
```
Trying to install PythonOT leads to some compatibility issue with Python39:
```
(py39) [syz@archlinux ~]$ conda install -c conda-forge pot
```

```UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pot -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.9
```

For comparison,
```
pip install pot
```
installs pot=0.7.0 without any complaints.

### To Reproduce
```
conda create -n py39 python=3.9
conda activate py39
conda install -c conda-forge pot
```
Error details:
```
(py39) [syz@archlinux ~]$ conda install -c conda-forge pot
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                   

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pot -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.33=0
  - pot -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - python=3.9 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.33
```

#### Code sample
See above

### Expected behavior
Conda should be able to install POT successfully.

### Environment (please complete the following information):

Environment: Linux (Python 3.9.6) with `conda`

Output of the following code snippet:
```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import ot; print("POT", ot.__version__)
```
```
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform; print(platform.platform())
Linux-5.13.9-arch1-1-x86_64-with-glibc2.33
>>> import sys; print("Python", sys.version)
Python 3.9.6 (default, Jul 30 2021, 16:35:19) 
[GCC 7.5.0]
>>> import numpy; print("NumPy", numpy.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'
>>> import scipy; print("SciPy", scipy.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
>>> import ot; print("POT", ot.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ot'
```

**Comment by rflamary** [comment]
Hello @zsteve thank you for thsi report. We do not have conda-forge packages for python3.9 but it should work with pip.

@djsutherland, you did the initial conda-forge packaging, could you have a look please?

**Comment by zsteve** [comment]
> Hello @zsteve thank you for thsi report. We do not have conda-forge packages for python3.9 but it should work with pip.
> 
> @djsutherland, you did the initial conda-forge packaging, could you have a look please?

Thanks, makes sense. The reason I ask is that currently we have integrated some of POT with Julia, which relies specifically on conda to install python packages (at least, that is the default behaviour). Currently this issue is causing some of our CI to fail.

**Comment by rflamary** [comment]
Repopened because the conda-forge is still not pre-compiled ;)

**Comment by zsteve** [comment]
Just following up on this! Julia/PyCall for some reason only uses conda for installation, so an upstream fix would be the simplest solution. Otherwise I can look at workarounds.

**Comment by rflamary** [comment]
Hello,

Conda forge for POT is here a,nd the PR for 3.9 is indeed failing, but I don't have the slightest idea how to debug it (But i will merge any working debugging ;) ). 

https://github.com/conda-forge/pot-feedstock
