### ISSUE TITLE
Bug in FGW barycenter example

### ISSUE THREAD

**Issue by rflamary** [PythonOT/POT#489]
## Describe the bug

We have a bug when running the FGW barycenter example (not in my local install or on github action but on circleci)

```
Unexpected failing examples:
/home/circleci/project/examples/gromov/plot_barycenter_fgw.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/circleci/project/examples/gromov/plot_barycenter_fgw.py", line 164, in <module>
    Cs = [shortest_path(nx.adjacency_matrix(x, dtype=np.int_)) for x in X0]
  File "/home/circleci/project/examples/gromov/plot_barycenter_fgw.py", line 164, in <listcomp>
    Cs = [shortest_path(nx.adjacency_matrix(x, dtype=np.int_)) for x in X0]
  File "_shortest_path.pyx", line 198, in scipy.sparse.csgraph._shortest_path.shortest_path
  File "_shortest_path.pyx", line 588, in scipy.sparse.csgraph._shortest_path.dijkstra
ValueError: Buffer dtype mismatch, expected 'const int' but got 'long'
```

that appeared recently (no idea why and it tried different dtypes nothing works).

I changed the conf.py file to skip the example for the moment but we need to find a way to make it work.

When this is fixed we need to edit this line to remove the skip

https://github.com/PythonOT/POT/blob/80461cd64f679de58cf854a8d6d409a684143cb7/docs/source/conf.py#L360

### Environment (please complete the following information):
- OS (e.g. MacOS, Windows, Linux):
- Python version:
- How was POT installed (source, `pip`, `conda`):
- Build command you used (if compiling from source):
- Only for GPU related bugs:
    - CUDA version:
    - GPU models and configuration:
    - Any other relevant information:

Output of the following code snippet:
```python
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import ot; print("POT", ot.__version__)
```

**Comment by rflamary** [comment]
Solved in #495 by converting the matrix to dense...
